products:
  template:
    build:
      main-pkg: ./template
    dist:
      disters:
        manual:
          type: manual
          config:
            extension: tgz
          input-dir:
            path: ./template/
          script: |
            #!/bin/bash
            set -ex
            ./scripts/copyProducts.sh  $PRODUCT $PRODUCT
            cp -r template/bin $DIST_WORK_DIR
            cd $DIST_WORK_DIR; tar -czf $DIST_DIR/$DIST_ARTIFACT_0 bin/
